# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Monkey1Wizard.WDA
PackageVersion: 0.1.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wda.exe
  PortableCommandAlias: wda
Commands:
- wda
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/monkey1wizard/web-design-anchor/releases/download/v0.1.0/wda-v0.1.0-windows-x64.zip
  InstallerSha256: 47037b128be897b42ce009116085c431638f75335a466bdc2cf7ff2f060cf3cb
- Architecture: arm64
  InstallerUrl: https://github.com/monkey1wizard/web-design-anchor/releases/download/v0.1.0/wda-v0.1.0-windows-arm64.zip
  InstallerSha256: 34aa17b725293def6b6ff50f1a4a248d90f25eadaf857578770fed916d4aa22b
ManifestType: installer
ManifestVersion: 1.6.0
